import { defineConfig } from 'vite';
import type { Plugin, ResolvedServerUrls } from 'vite';
import { resolve } from 'node:path';
import { readdirSync, statSync, existsSync, cpSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';

/**
 * Auto-discovers examples/<name>/index.html entries and prints their URLs
 * after Vite's own "Local" / "Network" URL block, so you don't have to
 * remember the paths.
 *
 * twm-session is the only example that still ships a source index.html
 * (it is the orchestrator — not a Layer‑1 compiled‑C demo).
 */
function listDemoEntries(): { name: string; path: string }[] {
  const examplesDir = resolve(__dirname, 'examples');
  if (!existsSync(examplesDir)) return [];
  return readdirSync(examplesDir)
    .filter((name) => {
      const entry = resolve(examplesDir, name, 'index.html');
      return statSync(resolve(examplesDir, name)).isDirectory() && existsSync(entry);
    })
    .map((name) => ({ name, path: `/examples/${name}/` }));
}

/** Demos that import from src/ — Vite must bundle these. */
function bundlableEntries(): { name: string; path: string }[] {
  return listDemoEntries().filter((d) => d.name === 'twm-session');
}

/**
 * Layer‑1 demos: pure‑C examples compiled with emscripten and linked via
 * emx11_finalize_demo().  They have a CMakeLists.txt but NO user‑written
 * index.html — the HTML is auto‑generated by this config so the user
 * never writes a line of JS or HTML.
 *
 * twm is excluded even though it has a CMakeLists.txt because it is not
 * a standalone demo — it only exists to be spawned by twm‑session.
 */
function discoverLayer1Demos(): string[] {
  const examplesDir = resolve(__dirname, 'examples');
  if (!existsSync(examplesDir)) return [];
  return readdirSync(examplesDir)
    .filter((name) => {
      const dir = resolve(examplesDir, name);
      if (!statSync(dir).isDirectory()) return false;
      // twm-session has index.html → handled by bundlableEntries
      if (existsSync(resolve(dir, 'index.html'))) return false;
      // twm is a build artifact for twm-session, not a standalone demo
      if (name === 'twm') return false;
      return existsSync(resolve(dir, 'CMakeLists.txt'));
    });
}

/** Auto-generated HTML for a Layer‑1 demo.  Imports the Emscripten ES6
 *  module from /artifacts/<name>/<name>.js and calls the default factory.
 *  Identical to what a user *would* write — but the user shouldn't have
 *  to write it.  That's the whole promise of Layer 1. */
function layer1DemoHtml(name: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${name} - EmX11</title>
  </head>
  <body>
    <script type="module">
      const factory = (await import('/artifacts/${name}/${name}.js')).default;
      await factory();
    </script>
  </body>
</html>
`;
}

function printDemoUrls(): Plugin {
  const layer1 = discoverLayer1Demos();
  const demos = listDemoEntries();
  return {
    name: 'emx11-print-demo-urls',
    configureServer(server) {
      const originalPrint = server.printUrls.bind(server);
      server.printUrls = () => {
        originalPrint();
        if (demos.length === 0 && layer1.length === 0) return;
        const urls: ResolvedServerUrls | null = server.resolvedUrls;
        const bases = urls ? [...urls.local, ...urls.network] : [];
        const base = bases[0]?.replace(/\/$/, '') ?? '';
        // eslint-disable-next-line no-console
        console.log('\n  \x1b[1mDemos\x1b[0m:');
        for (const d of demos) {
          // eslint-disable-next-line no-console
          console.log(`    \x1b[36m${d.name.padEnd(10)}\x1b[0m ${base}${d.path}`);
        }
        for (const name of layer1) {
          // eslint-disable-next-line no-console
          console.log(`    \x1b[36m${name.padEnd(10)}\x1b[0m ${base}/examples/${name}/`);
        }
        // eslint-disable-next-line no-console
        console.log('');

        // Warn if native artifacts are missing.
        const artifacts = resolve(__dirname, 'build/artifacts');
        if (!existsSync(artifacts)) {
          // eslint-disable-next-line no-console
          console.warn(
            '\x1b[33m  build/artifacts/ not found. ' +
              "Run 'pnpm build:native' first, otherwise demos will fail " +
              'with "returned HTML instead of code".\x1b[0m\n',
          );
        }
      };
    },
  };
}

/**
 * Serve build/artifacts/**​/* as static files — no Vite transform.
 *
 * Emscripten's MODULARIZE=1+EXPORT_ES6=1 output is a pre-built artifact,
 * not source code.  Vite's import-analysis scans every .js file with
 * `export default` and chokes on the minified 250 KB blob full of
 * emscripten runtime internals (new URL, import.meta.url, etc.).
 *
 * This middleware runs before Vite's own transform middleware and serves
 * the raw file straight from disk, so the build artifact passes through
 * to the browser untouched.  It also serves the sibling .wasm and .data
 * files that Emscripten fetches at runtime.
 *
 * Maps URL path /artifacts/* → disk path build/artifacts/*.
 */
function serveBuildArtifactsRaw(): Plugin {
  return {
    name: 'emx11-serve-build-artifacts-raw',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url) return next();
        const pathname = req.url.split('?')[0];
        if (!pathname.startsWith('/artifacts/')) {
          return next();
        }
        const filePath = resolve(__dirname, 'build' + pathname);
        if (!existsSync(filePath)) return next();
        const ext = pathname.split('.').pop()?.toLowerCase();
        const mimeTypes: Record<string, string> = {
          html: 'text/html',
          js: 'application/javascript',
          wasm: 'application/wasm',
          data: 'application/octet-stream',
        };
        res.setHeader('Content-Type', mimeTypes[ext ?? ''] ?? 'application/octet-stream');
        res.setHeader('Cache-Control', 'no-cache');
        res.statusCode = 200;
        res.end(readFileSync(filePath));
      });
    },
  };
}

/**
 * Serve auto-generated HTML for Layer‑1 demos at /examples/<name>/.
 *
 * These demos have no checked-in index.html — the HTML is generated
 * on the fly so the user never writes a line of JS or HTML.  This is
 * the core of the Layer 1 (zero‑JS) guarantee.
 */
function serveLayer1GeneratedHtml(): Plugin {
  const layer1 = new Set(discoverLayer1Demos());
  return {
    name: 'emx11-serve-layer1-generated-html',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url) return next();
        const pathname = req.url.split('?')[0];
        // Match /examples/<name>/ or /examples/<name>/index.html
        const m = pathname.match(/^\/examples\/([^/]+)\/(index\.html)?$/);
        if (!m || !layer1.has(m[1]!)) return next();
        res.setHeader('Content-Type', 'text/html');
        res.setHeader('Cache-Control', 'no-cache');
        res.statusCode = 200;
        res.end(layer1DemoHtml(m[1]!));
      });
    },
  };
}

/**
 * Copy build/artifacts/ → dist/artifacts/ at the end of `vite build`.
 *
 * Demos `import('/artifacts/<name>/<name>.js')` and Emscripten
 * fetches the sibling `.wasm`. In dev these resolve via the raw-serve
 * middleware. In preview / static deploys, only `dist/` is served, so
 * unless the artifacts are mirrored into `dist/` the URLs hit the SPA
 * fallback (`index.html`) and dynamic-import fails with
 * "Unexpected token '<'".
 *
 * Uses fs.cpSync (Node ≥ 16.7); cheap because the cmake outputs are a
 * handful of MB total. Skips silently if the artifacts directory is
 * missing — that just means `pnpm build:native` hasn't run yet, and
 * the JS-only build is still useful (e.g. CI typecheck builds).
 */
function copyBuildArtifacts(): Plugin {
  return {
    name: 'emx11-copy-build-artifacts',
    apply: 'build',
    closeBundle() {
      const src = resolve(__dirname, 'build/artifacts');
      const dst = resolve(__dirname, 'dist/artifacts');
      if (!existsSync(src)) {
        // eslint-disable-next-line no-console
        console.warn(
          `[emx11] build/artifacts/ not found; skipping dist copy. ` +
            `Run 'pnpm build:native' first if you need a runnable preview.`,
        );
        return;
      }
      cpSync(src, dst, { recursive: true });
    },
  };
}

/**
 * Write auto-generated HTML for Layer‑1 demos into dist/examples/.
 *
 * These demos have no checked-in index.html — the HTML is generated
 * during the build so the user never writes a line of JS or HTML.
 * The bundled twm-session demo is handled by Vite's own HTML output.
 */
function writeLayer1BuildHtml(): Plugin {
  return {
    name: 'emx11-write-layer1-build-html',
    apply: 'build',
    closeBundle() {
      for (const name of discoverLayer1Demos()) {
        const dstDir = resolve(__dirname, 'dist', 'examples', name);
        if (!existsSync(dstDir)) mkdirSync(dstDir, { recursive: true });
        writeFileSync(resolve(dstDir, 'index.html'), layer1DemoHtml(name));
      }
    },
  };
}

export default defineConfig({
  root: '.',
  publicDir: 'public',

  plugins: [
    serveLayer1GeneratedHtml(),
    serveBuildArtifactsRaw(),
    printDemoUrls(),
    copyBuildArtifacts(),
    writeLayer1BuildHtml(),
  ],

  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },

  server: {
    port: 5173,
    headers: {
      // Required for SharedArrayBuffer (used by emscripten pthreads / JSPI Worker mode)
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
    fs: {
      // Allow serving wasm artifacts from the out-of-root build directory.
      allow: ['.', 'build'],
    },
  },

  build: {
    target: 'es2022',
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
    rollupOptions: {
      external: [/^\/artifacts\//],
      input: Object.fromEntries(
        [
          ['main', resolve(__dirname, 'index.html')],
          ...bundlableEntries().map((d) => [d.name, resolve(__dirname, `examples/${d.name}/index.html`)]),
        ],
      ),
    },
  },

  assetsInclude: ['**/*.wasm'],

  worker: {
    /* Emit workers as ES modules so dynamic `import(glueUrl)` inside the
     * Client Worker sees the glue's `export default` -- Emscripten's
     * MODULARIZE=1+EXPORT_ES6=1 output is ESM, and a classic-script
     * worker can't import it. */
    format: 'es',
  },

  optimizeDeps: {
    // Emscripten glue is ESM-ish but does odd things; exclude from pre-bundling.
    exclude: ['@/loader/wasm'],
  },
});
